[package]
name = "voting"
version = "0.0.1"
edition = "2024.beta" # <--- ADICIONE ESTA LINHA

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
event_system = "0x0"